### PR TITLE
Create enums for values

### PR DESCRIPTION
**Pull request by kbickar**
Replace values of digits or single letters with enum classes for type purposes.

Fix issue where the side  of 0, 1, or None all set the right side `SIDES_FULL[side] if side else None` as noted in #10 

@mfugate1 and @[mjn138](https://github.com/mjn138), can you please review as I can't test the split functionality

### CODE REVIEW

**Comment by mjn138** [comment]
Getting errors - first it couldn't import MASSSAGE_SPEEDS (I think because it's MASSAGE_SPEED in the Consts.py file).  But now I'm getting "cannot import name 'Mode' from 'asyncsleepiq.consts'" which I think might be also missing in the Consts.py file?

**Comment by mjn138** [comment]
I am not sure what should've been in the consts.py file as I don't have Massage capabilities on my bed (and I'm not that great at reading code), but I added some fake stuff in there, and now the Left Bed Head position is controllable, so you've fixed that, thanks!

**Comment by kbickar** [comment]
Ah always press the "Save All" button before you commit, can you take a look again?

**Comment by mjn138** [comment]
Haha works now, thanks!

**Pull request merged**
